apiVersion: v1
kind: Secret
metadata:
  name: karakeep-secret
  namespace: default
type: Opaque
stringData:
  encryption_key: ENC[AES256_GCM,data:RtkQNSolkUTWqlBApyxHuXtBZwA=,iv:RdEiQkPJxuDT4Vs3cjfaHAFKKjvl/MKPgyXGPDpxgKY=,tag:D3NctUihtozK+bk+x3uF0Q==,type:str]
  meilisearch_master_key: ENC[AES256_GCM,data:JvXHfskICCZrXmi7XGjVnLFTf28=,iv:jKcFeoM1uRrobR0N+6HZwliScym+rnHcLzwWjStP1Bs=,tag:kOx5uwSpvngA/WucnC4UEg==,type:str]
sops:
  age:
    - recipient: age12wyktvsrgcq2ew20w4s9wj3zgculzg9ck3lr47nhzjrf3qku847qmufzte
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlcmxWUUdNWk9tbkJDSm03
        azBmMHFHZlFTNG96R3AyOU5RREQxZk9QQ1JRClQ3NTZkc2taVDJ4TlJPMWhCbHpn
        THQwdFF3eGRzRHd6ejI1cU1qTTN4ZTAKLS0tIHFqa3VNUG1EVEdLSW51alJ6eHBO
        N3ByM0FrTStMZ25ENXlSaUxEWFJESDgKCcCezrxEB/lxdOU2K7HojhRktyD0DWzu
        Y7IbXa+E/H6AvIXFG5meCYV6Hno6DzSrXuboCRzMoW0rqLa1YCiLuA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-26T18:52:36Z"
  mac: ENC[AES256_GCM,data:+4ulLvCGFyxR7DJPnSYqkt5D21Oi3Ckhhsv+H7HkTGa2BSEN+7cWBLbGAT/ML0Pzvr+vzc5FQlkE2VnDnpbx0sNVKRev+IbS4sd5vt3tG14o8DH99zjeI8aur56DGw4WuWQacHJ4m4/si6fEgdo8euASzz558wzlTLPtSxl/rZY=,iv:6bvYKs4GxqhL6uN0Z4sLzdXuUrVDgJP1dcDhB7XFviw=,tag:+c3MjZgpucLDZzxhq+5hUA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
